import 'package:flutter/material.dart';

const green = Color(0xff216847), ink = Color(0xff173e2c);
void main() => runApp(const FarmOneApp());

class FarmOneApp extends StatelessWidget {
  const FarmOneApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'FarmOne',
    theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: green), scaffoldBackgroundColor: const Color(0xfff7f8f3)),
    home: const AppShell(),
  );
}

class AppShell extends StatefulWidget { const AppShell({super.key}); @override State<AppShell> createState() => _AppShellState(); }
class _AppShellState extends State<AppShell> {
  int page = 0;
  final views = const [Dashboard(), Marketplace(), Orders(), Logistics()];
  final titles = const ['FarmOne', 'Marketplace', 'My Orders', 'Logistics'];
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(backgroundColor: const Color(0xfff7f8f3), surfaceTintColor: Colors.transparent, title: Row(children: [Container(padding: const EdgeInsets.all(7), decoration: BoxDecoration(color: green, borderRadius: BorderRadius.circular(9)), child: const Icon(Icons.spa_rounded, color: Color(0xffdcef8d))), const SizedBox(width: 9), Text(titles[page], style: const TextStyle(fontWeight: FontWeight.w800, color: ink))]), actions: [IconButton(onPressed: () {}, icon: const Badge(child: Icon(Icons.notifications_none_rounded)))]),
    body: SafeArea(child: views[page]),
    floatingActionButton: page < 2 ? FloatingActionButton.extended(onPressed: () => listingSheet(context), backgroundColor: green, icon: const Icon(Icons.add), label: const Text('List produce')) : null,
    bottomNavigationBar: NavigationBar(selectedIndex: page, onDestinationSelected: (i) => setState(() => page = i), destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'Home'), NavigationDestination(icon: Icon(Icons.storefront_outlined), selectedIcon: Icon(Icons.storefront), label: 'Market'), NavigationDestination(icon: Icon(Icons.receipt_long_outlined), selectedIcon: Icon(Icons.receipt_long), label: 'Orders'), NavigationDestination(icon: Icon(Icons.local_shipping_outlined), selectedIcon: Icon(Icons.local_shipping), label: 'Logistics')]),
  );
}

class Dashboard extends StatelessWidget {
  const Dashboard({super.key});
  @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 8, 20, 100), children: [
    const Label('TUESDAY, 03 SEPTEMBER'), const SizedBox(height: 4), const Text('Good morning, Priya ☀', style: TextStyle(fontSize: 28, fontWeight: FontWeight.w800, color: ink)), const SizedBox(height: 20),
    Container(height: 202, padding: const EdgeInsets.all(22), decoration: BoxDecoration(color: green, borderRadius: BorderRadius.circular(20)), child: Stack(children: [const Positioned(right: -9, bottom: -7, child: Text('🌾', style: TextStyle(fontSize: 112))), Column(crossAxisAlignment: CrossAxisAlignment.start, children: const [Label('YOUR FARM AT A GLANCE', color: Color(0xffcae2a2)), SizedBox(height: 10), Text('A fairer harvest\nstarts here.', style: TextStyle(fontSize: 26, height: 1.08, fontWeight: FontWeight.w800, color: Colors.white)), SizedBox(height: 10), Text('Sell directly and keep more of what you grow.', style: TextStyle(fontSize: 12, color: Color(0xffd9e9df)))])])),
    const SizedBox(height: 18), const Row(children: [Expanded(child: Stat(Icons.currency_rupee, Color(0xfff8dccb), 'ESTIMATED EARNINGS', '₹48,250', '↑ 12.5% this month')), SizedBox(width: 12), Expanded(child: Stat(Icons.inventory_2_outlined, Color(0xfff8edc7), 'ACTIVE LISTINGS', '04', '2 need attention'))]),
    const SizedBox(height: 24), heading('Your active listings', 'View all'), const SizedBox(height: 8), ...produce.take(3).map((p) => Listing(item: p)),
    const SizedBox(height: 22), heading('Demand in your area', 'Next 7 days'), const Demand(), const SizedBox(height: 22), heading('Orders awaiting response', '3 new'), const OrderSummary(),
  ]);
}

const produce = [('🍅', 'Fresh Tomatoes', 'Grade A · 800 kg available', '₹28', 0xfffbe3db), ('🧅', 'Red Onions', 'Premium · 1,200 kg available', '₹24', 0xffeee4f6), ('🍇', 'Thompson Grapes', 'Grade A · 350 kg available', '₹72', 0xffe2f0e3), ('🫑', 'Green Capsicum', 'Grade A · 500 kg available', '₹36', 0xffe4f1dd), ('🍎', 'Pomegranates', 'Export quality · 280 kg', '₹96', 0xfff7e2df)];

class Marketplace extends StatelessWidget { const Marketplace({super.key}); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 10, 20, 100), children: [const Label('SELL DIRECTLY'), const SizedBox(height: 6), const Text('Fresh from your farm', style: TextStyle(fontSize: 27, fontWeight: FontWeight.w800, color: ink)), const SizedBox(height: 8), const Text('Reach households and reliable buyers without the middle layer.', style: TextStyle(color: Color(0xff6b8274))), const SizedBox(height: 19), TextField(decoration: InputDecoration(hintText: 'Search produce or buyers', prefixIcon: const Icon(Icons.search), filled: true, fillColor: Colors.white, border: OutlineInputBorder(borderRadius: BorderRadius.circular(13), borderSide: BorderSide.none))), const SizedBox(height: 16), ...produce.map((p) => Listing(item: p))]); }

class Orders extends StatefulWidget { const Orders({super.key}); @override State<Orders> createState() => _OrdersState(); }
class _OrdersState extends State<Orders> { final orders = <String>['Meera Restaurants|250 kg Fresh Tomatoes|₹29 / kg|06 Sep', 'Mumbai Fresh Mart|600 kg Red Onions|₹25 / kg|07 Sep', 'Aarav Grocers|140 kg Thompson Grapes|₹74 / kg|08 Sep']; @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [const Label('ORDER MANAGEMENT'), const SizedBox(height: 6), const Text('Incoming orders', style: TextStyle(fontSize: 27, fontWeight: FontWeight.w800, color: ink)), const SizedBox(height: 8), const Text('Accept the orders that work best for your harvest.', style: TextStyle(color: Color(0xff6b8274))), const SizedBox(height: 18), ...orders.asMap().entries.map((e) { final p = e.value.split('|'); return Card(child: Padding(padding: const EdgeInsets.all(17), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [const CircleAvatar(backgroundColor: Color(0xffddeef3), child: Icon(Icons.store, color: Color(0xff31728f))), const SizedBox(width: 10), Expanded(child: Text(p[0], style: const TextStyle(fontWeight: FontWeight.w800))), Text(p[2], style: const TextStyle(fontWeight: FontWeight.w800, color: green))]), const SizedBox(height: 14), Text(p[1]), const SizedBox(height: 4), Text('Delivery by ${p[3]}', style: const TextStyle(fontSize: 12, color: Color(0xff72877a))), const SizedBox(height: 14), Row(mainAxisAlignment: MainAxisAlignment.end, children: [TextButton(onPressed: () => setState(() => orders.removeAt(e.key)), child: const Text('Decline')), const SizedBox(width: 8), FilledButton(onPressed: () { setState(() => orders.removeAt(e.key)); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Order accepted — buyer notified.'))); }, style: FilledButton.styleFrom(backgroundColor: green), child: const Text('Accept order'))])]))); })]); }

class Logistics extends StatelessWidget { const Logistics({super.key}); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [const Label('SMART COLLECTION'), const SizedBox(height: 6), const Text('Logistics planner', style: TextStyle(fontSize: 27, fontWeight: FontWeight.w800, color: ink)), const SizedBox(height: 8), const Text('Combine nearby pickups and lower the cost per kilogram.', style: TextStyle(color: Color(0xff6b8274))), const SizedBox(height: 22), Container(height: 190, decoration: BoxDecoration(color: const Color(0xffdcecd5), borderRadius: BorderRadius.circular(18)), child: Stack(children: [const Center(child: Icon(Icons.route_rounded, size: 100, color: Color(0xff82ad86))), Positioned(top: 25, left: 34, child: pin('Nashik')), Positioned(right: 27, bottom: 34, child: pin('Mumbai')), const Positioned(right: 15, top: 14, child: Chip(label: Text('165 km · 2h 54m')))])), const SizedBox(height: 18), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Label('TODAY\'S SUGGESTED ROUTE'), const SizedBox(height: 9), const Text('Nashik collection → Mumbai', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), const SizedBox(height: 18), ...['08:30  FarmOne collection hub', '09:15  Priya Nair farm · 800 kg tomatoes', '10:00  Green Valley FPO · 1,200 kg onions', '13:45  Mumbai wholesale market'].map((x) => Padding(padding: const EdgeInsets.only(bottom: 13), child: Row(children: [const Icon(Icons.location_on, size: 17, color: Color(0xff54a16c)), const SizedBox(width: 9), Text(x, style: const TextStyle(fontSize: 12))]))), const Divider(), const Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text('2,000 kg load'), Text('₹2.10 / kg', style: TextStyle(fontWeight: FontWeight.bold, color: green))])]))]); static Widget pin(String label) => Column(children: [const Icon(Icons.location_pin, color: Color(0xffe56d55)), Text(label, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w700))]); }

class Label extends StatelessWidget { final String text; final Color color; const Label(this.text, {super.key, this.color = const Color(0xff7a8f81)}); @override Widget build(BuildContext context) => Text(text, style: TextStyle(fontSize: 10, fontWeight: FontWeight.w800, letterSpacing: 1.1, color: color)); }
class Stat extends StatelessWidget { final IconData icon; final Color color; final String label, value, sub; const Stat(this.icon, this.color, this.label, this.value, this.sub, {super.key}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(9)), child: Icon(icon, size: 20, color: ink)), const SizedBox(height: 13), Label(label), Text(value, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w800)), const SizedBox(height: 4), Text(sub, style: const TextStyle(fontSize: 10, color: Color(0xff358961)))]))); }
Widget heading(String title, String action) => Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(title, style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w800, color: ink)), Text(action, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: green))]);
class Listing extends StatelessWidget { final (String, String, String, String, int) item; const Listing({super.key, required this.item}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(13), child: Row(children: [Container(width: 47, height: 47, alignment: Alignment.center, decoration: BoxDecoration(color: Color(item.$5), borderRadius: BorderRadius.circular(12)), child: Text(item.$1, style: const TextStyle(fontSize: 25))), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(item.$2, style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 3), Text(item.$3, style: const TextStyle(fontSize: 11, color: Color(0xff74897b)))])), Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text(item.$4, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 15)), const Text('/ kg', style: TextStyle(fontSize: 10, color: Color(0xff74897b))), const SizedBox(height: 5), const Text('LIVE', style: TextStyle(fontSize: 8, fontWeight: FontWeight.w800, color: green))])]))); }
class Demand extends StatelessWidget { const Demand({super.key}); @override Widget build(BuildContext context) => Card(color: const Color(0xfff5f8e9), child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Label('HIGH DEMAND', color: Color(0xff63813c)), const SizedBox(height: 7), const Text('Tomatoes are trending 🍅', style: TextStyle(fontSize: 17, fontWeight: FontWeight.w800)), const Text('Demand is expected to rise by 18% next week.', style: TextStyle(fontSize: 12, color: Color(0xff678073))), const SizedBox(height: 15), bar('Tomatoes', .86, '+18%'), bar('Onions', .61, '+7%'), bar('Grapes', .42, '−3%', down: true)]))); Widget bar(String n, double progress, String change, {bool down = false}) => Padding(padding: const EdgeInsets.only(top: 10), child: Row(children: [SizedBox(width: 70, child: Text(n, style: const TextStyle(fontSize: 11))), Expanded(child: LinearProgressIndicator(value: progress, minHeight: 7, borderRadius: BorderRadius.circular(10), backgroundColor: const Color(0xffe4ebdd), valueColor: const AlwaysStoppedAnimation(Color(0xff7cae59)))), const SizedBox(width: 10), Text(change, style: TextStyle(fontWeight: FontWeight.bold, fontSize: 11, color: down ? const Color(0xffbb6d60) : green))])); }
class OrderSummary extends StatelessWidget { const OrderSummary({super.key}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(15), child: Row(children: [const CircleAvatar(backgroundColor: Color(0xffddeef3), child: Text('MR', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Color(0xff31728f)))), const SizedBox(width: 11), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Meera Restaurants', style: TextStyle(fontWeight: FontWeight.w800)), Text('Needs 250 kg Fresh Tomatoes', style: TextStyle(fontSize: 11, color: Color(0xff72877a)))])), FilledButton(onPressed: () => ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Order accepted — buyer notified.'))), style: FilledButton.styleFrom(backgroundColor: green), child: const Text('Accept'))]))); }
void listingSheet(BuildContext context) { final key = GlobalKey<FormState>(), name = TextEditingController(); showModalBottomSheet(context: context, isScrollControlled: true, builder: (sheetContext) => Padding(padding: EdgeInsets.fromLTRB(24, 24, 24, MediaQuery.of(sheetContext).viewInsets.bottom + 24), child: Form(key: key, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [const Label('NEW MARKETPLACE LISTING'), const SizedBox(height: 7), const Text('What are you harvesting?', style: TextStyle(fontSize: 24, fontWeight: FontWeight.w800)), const SizedBox(height: 18), TextFormField(controller: name, decoration: const InputDecoration(labelText: 'Produce name', border: OutlineInputBorder()), validator: (v) => v == null || v.isEmpty ? 'Please add a produce name' : null), const SizedBox(height: 12), TextFormField(keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Quantity available (kg)', border: OutlineInputBorder())), const SizedBox(height: 12), TextFormField(keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Your price per kg', border: OutlineInputBorder())), const SizedBox(height: 18), SizedBox(width: double.infinity, child: FilledButton(onPressed: () { if (key.currentState!.validate()) { Navigator.pop(sheetContext); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${name.text} is now live in the marketplace.'))); } }, style: FilledButton.styleFrom(backgroundColor: green, padding: const EdgeInsets.all(15)), child: const Text('Publish listing')))]))); }
